/// Generated by AssetsRefGenerator on 2022/12/22
class Res {
  static const String camera = "assets/camera.png";
  static const String gallery = "assets/gallery.png";
  static const String splash_image = "assets/splash_image.png";
}
